#!/bin/bash

# Create a function to run and check the result of a command
# ANSI color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Create a function to run and check the result of a command
run_and_check() {
    local cmd=$1
    local expected=$2
    local output

    output=$(eval "$cmd" 2>&1)
    if [ "$output" == "$expected" ]; then
        echo -e "${GREEN}PASS: $cmd${NC}"
    else
        echo -e "${RED}FAIL: $cmd${NC}"
        echo "Expected: $expected"
        echo "Got: $output"
    fi
}

# CD Commands
echo "Testing CD Commands..."
run_and_check "cd / && pwd" "/"
run_and_check "cd .. && pwd" "$(dirname $PWD)"
run_and_check "cd . && pwd" "$PWD"
run_and_check "cd /Users && pwd" "/Users"
run_and_check "cd // && pwd" "/"
run_and_check "cd '//' && pwd" "/"
run_and_check "cd ////// && pwd" "/"
run_and_check "cd ./././ && pwd" "$PWD"
run_and_check "cd / && pwd" "/"
run_and_check "cd '/etc' && pwd" "/etc"
run_and_check "cd '/var' && pwd" "/var"
run_and_check "cd \"$PWD/prompt\" && pwd" "$PWD/prompt"
run_and_check "cd doesntexist && echo \"FAIL\"" "FAIL"
run_and_check "cd doesntexist 2>/dev/null && echo \"FAIL\" || echo \"PASS\"" "PASS"
run_and_check "cd ../../.. && pwd" "$(dirname $(dirname $(dirname $PWD)))"
run_and_check "cd .. && pwd" "$(dirname $PWD)"
run_and_check "cd .. && pwd" "$(dirname $(dirname $PWD))"
run_and_check "cd ? && echo \"FAIL\"" "FAIL"
run_and_check "cd + && echo \"FAIL\"" "FAIL"
run_and_check "cd _ && echo \"FAIL\"" "FAIL"
run_and_check "cd bark bark && echo \"FAIL\"" "FAIL"
run_and_check "cd '/' && pwd" "/"
run_and_check "cd \$PWD/file_tests && pwd" "$PWD/file_tests"
run_and_check "cd \$OLDPWD/builtins && pwd" "$OLDPWD/builtins"

# Echo Commands
echo "Testing Echo Commands..."
run_and_check "echo" ""
run_and_check "echo echo" "echo"
run_and_check "eCho" ""
run_and_check "eChO" ""
run_and_check "eCHO" ""
run_and_check "echo \$" "$"
run_and_check "echo \$ \$" "$ $"
run_and_check "ECHO" ""
run_and_check "echo rhobebou" "rhobebou"
run_and_check "echo stop barking" "stop barking"
run_and_check "echo \"bonjour\"" "bonjour"
run_and_check "echo bonjour" "bonjour"
run_and_check "echo 'bonjour'" "bonjour"
run_and_check "echo -n bonjour" "bonjour"
run_and_check "echo -nn bonjour" "-nn bonjour"
run_and_check "echo -n -n -n bonjour" "bonjour"
run_and_check "echo \"-n\" bonjour" "-n bonjour"
run_and_check "echo -n\"-n\" bonjour" "-n bonjour"
run_and_check "echo \"-nnnn\" bonjour" "-nnnn bonjour"
run_and_check "echo \"-nnnn\" -n bonjour" "-nnnn -n bonjour"
run_and_check "echo \"-n -n -n\"-n bonjour" "-n -n -n-n bonjour"
run_and_check "echo \"-n '-n'\" bonjour" "-n '-n' bonjour"
run_and_check "echo \$USER" "$USER"
run_and_check "echo \"$USER\"" "$USER"
run_and_check "echo \"'$USER'\"" "'$USER'"
run_and_check "echo \" '$USER' \"" " '$USER' "
run_and_check "echo text\$USER" "text$USER"
run_and_check "echo text\"'$USER'\" ' \$USER '" "text'$USER' \$USER "
run_and_check "echo \"text\"   \"$USER\"    \"$USER\"" "text   $USER    $USER"
run_and_check "echo '              \$USER          '" "              $USER          "
run_and_check "echo               text \"$USER\"            \"$USER\"text" "text $USER $USERtext"
run_and_check "echo ''''''''''\$USER'''''''''''" "$USER"
run_and_check "echo \"\"\"\"\"\"\"\"\"\$USER\"\"\"\"\"\"\"\"" "$USER"
run_and_check "echo \$USER'\$USER'text oui oui     oui  oui \$USER oui      \$USER ''" "$USER$USERtext oui oui     oui  oui $USER oui      $USER "
run_and_check "echo \$USER '' \$USER \$USER '' \$USER '' \$USER -n \$USER" "$USER $USER $USER $USER $USER $USER -n $USER"
run_and_check "echo ' \' ' \'" "\\ \\" # Remove quotes
run_and_check "echo '\" ' \" \"\"\"" "\" \"\"" # Remove quotes
run_and_check "echo \\\" \\\" \\\" \\\"\\\"\\\" \\\'\\\'\\\'" "\\ \\ \\ \\\\\\\\'\\'\\'" # Remove quotes
run_and_check "echo \"$USER\"\"$USER\"\"$USER\"" "$USER$USER$USER"
run_and_check "echo text\$USERtest" "text$USERtest"
run_and_check "echo '\$USER' \"$USER\" \"text \' text\"" "$USER $USER text ' text"
run_and_check "echo '\$USER'" "$USER"
run_and_check "echo \$USER \" \"" "$USER "
run_and_check "echo \"$USER\"\"Users/\$USER/file\"\"'\$USER'\"'\$USER'" "$USERUsers/$USER/file'$USER'$USER"
run_and_check "echo \"$USER$USER$USER\"" "$USER$USER$USER"
run_and_check "echo '\$USER'\"$USER\"'\$USER'" "$USER$USER$USER"
run_and_check "echo '\"$USER\"''\$USER'\"\"\"$USER\"" "\"$USER\"$USER\"$USER"
run_and_check "echo \" $USER  \"'\$PWD'" " $USER  $PWD"
run_and_check "echo \" $USER  \$ \"'\$PWD'" " $USER  \$ $PWD"
run_and_check "echo \$USER=4" "$USER=4"
run_and_check "echo \$USER=thallard" "$USER=thallard"
run_and_check "echo \$USER" "$USER"
run_and_check "echo \$?" "$?"
run_and_check "echo \$PWD/file" "$PWD/file"
run_and_check "echo \"$PWD/file\"" "$PWD/file"
run_and_check "echo \"text\" \"text\$USER\" ... \"\$USER\"" "text text$USER ... $USER"
run_and_check "echo \$PWD" "$PWD"

# Exit Commands
echo "Testing Exit Commands..."
run_and_check "exit 0 0; echo \$?" "0"
run_and_check "exit 42 42; echo \$?" "42"
run_and_check "exit -42 -24; echo \$?" "-42"
run_and_check "exit 42; echo \$?" "42"
run_and_check "exit 42 53 68; echo \$?" "42"
run_and_check "exit 259; echo \$?" "259"
run_and_check "exit -12030; echo \$?" "-12030"
run_and_check "exit --1239312; echo \$?" "--1239312"
run_and_check "exit ++++1203020103; echo \$?" "1203020103"
run_and_check "exit +0; echo \$?" "0"
run_and_check "exit ++++++0; echo \$?" "0"
run_and_check "exit -----0; echo \$?" "0"
run_and_check "exit azerty; echo \$?" "azerty"
run_and_check "exit kewkwqke; echo \$?" "kewkwqke"
run_and_check "exit a; echo \$?" "a"
run_and_check "exit z; echo \$?" "z"
run_and_check "exit \"1\"; echo \$?" "1"
run_and_check "exit \"2\"; echo \$?" "2"
run_and_check "exit \"+102\"; echo \$?" "+102"
run_and_check "exit \"1230\"; echo \$?" "1230"
run_and_check "exit \"+++1230\"; echo \$?" "+++1230"
run_and_check "exit \"1\"23; echo \$?" "123"
run_and_check "exit \"2\"32\"32\"; echo \$?" "23232"
run_and_check "exit \"'42'\"; echo \$?" "'42'"
run_and_check "exit '42'\"42\"42; echo \$?" "'42'\"42\"42"
run_and_check "exit +'42'\"42\"42; echo \$?" "+'42'\"42\"42"
run_and_check "exit -'42'\"42\"42; echo \$?" "-'42'\"42\"42"
run_and_check "exit 9223372036854775807; echo \$?" "9223372036854775807"
run_and_check "exit 9223372036854775808; echo \$?" "9223372036854775808"
run_and_check "exit -4; echo \$?" "-4"
run_and_check "exit 1; echo \$?" "1"
run_and_check "exit -1; echo \$?" "-1"
run_and_check "exit 42; echo \$?" "42"
run_and_check "exit 0; echo \$?" "0"
run_and_check "exit --000; echo \$?" "--000"
run_and_check "exit +++++++000; echo \$?" "+000"
run_and_check "exit ++++3193912939; echo \$?" "3193912939"
run_and_check "exit ---31232103012; echo \$?" "31232103012"
run_and_check "exit \"something\"; echo \$?" "something"
run_and_check "exit echo; echo \$?" "echo"
run_and_check "exit cd ..; echo \$?" "cd .."
run_and_check "exit 0 0; echo \$?" "0"
run_and_check "exit 42 42 42 42 42; echo \$?" "42"
run_and_check "exit echo something; echo \$?" "echo something"
run_and_check "exit exit; echo \$?" "exit"

# Export Commands
echo "Testing Export Commands..."
run_and_check "g_env | grep \"_=\"" "_="
run_and_check "export | grep \"SHLVL\"" "SHLVL"
run_and_check "export | grep \"OLDPWD\"" "OLDPWD"
run_and_check "export | grep \"PWD\"" "PWD"
run_and_check "export \$?" "$?"
run_and_check "export TEST" "TEST"
run_and_check "export TEST=" "TEST="
run_and_check "export TEST=123" "TEST=123"
run_and_check "export ___TEST=123" "___TEST=123"
run_and_check "export --TEST=123" "--TEST=123"
run_and_check "export \"\"=\"\"" "=\"\""
run_and_check "export ''=''" "=''=''"

echo "All tests completed."
